### ISSUE TITLE
I know this isn't the scope of the project... but

### ISSUE THREAD

**Issue by sirthomas** [yjose/awesome-new#8]
If you are interested in making this something big, and I do think this could become pretty popular.
I would suggest allowing users to make choices per app they want to go to. 
So visiting story.new lets me choose which website I'd like to open from then on, (medium,wordpress,blogspot) similar to how a mobile device shows you a prompt on how you want to open a file.

**Comment by yjose** [comment]
I am not sure if I totally understand , but this repo is only to collect `.new` domains, we didn't have the ability to update domain behaviors.
